
env:
  browser: true
  node: true
  jest: true
  es2021: true
settings:
  import/resolver:
    node: { 'extensions': ['.ts', '.tsx'] }
extends:
  - plugin:react/recommended
  - airbnb
  - 'plugin:jest/recommended'
  - 'plugin:import/errors'
  - 'plugin:import/warnings'
  - 'plugin:prettier/recommended'
  - 'plugin:react-hooks/recommended'
  - 'plugin:@typescript-eslint/recommended'
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: {
    import/no-extraneous-dependencies: ["error", {"devDependencies": true}],
    import/extensions: 0,
    react/prop-types: 1,
    no-console: 0,
    react/react-in-jsx-scope: 0,
    react/function-component-definition: 0,
    react/jsx-props-no-spreading: 0,
    'no-shadow': 'off',
    "default-param-last": 0,
    '@typescript-eslint/no-explicit-any': 'off',
    '@typescript-eslint/explicit-function-return-type': 'error',
    '@typescript-eslint/no-unused-vars': 'error',
    '@typescript-eslint/prefer-readonly-parameter-types': 0,
    '@typescript-eslint/no-shadow': [ 'error' ],
    'react/jsx-filename-extension': [ 2, { 'extensions': [ '.js', '.jsx', '.ts', '.tsx' ] } ],
    'max-len': [ 'warn', { 'code': 100 } ],
    'no-let': 'off',
    'jsx-a11y/no-noninteractive-element-to-interactive-role': 'off',
}
