env:
  browser: true
  node: true
  jest: true
  es2021: true
settings:
  import/resolver:
    node: { 'extensions': ['.js', '.jsx', '.ts', '.tsx'] }
extends:
  - plugin:react/recommended
  - airbnb
  - 'plugin:jest/recommended'
  - 'plugin:import/errors'
  - 'plugin:import/warnings'
  - 'plugin:prettier/recommended'
  - 'plugin:react-hooks/recommended'
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: {
    import/extensions: 0,
    react/prop-types: 1,
    no-console: 0,
    react/react-in-jsx-scope: 0,
    react/function-component-definition: 0,
    react/jsx-props-no-spreading: 0,
    'no-shadow': 'off'

}
