// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  "auth-page": string;
  "button-disabled": string;
  "button-enable": string;
  "change-form-text": string;
  error: string;
  eye: string;
  head: string;
  hide: string;
  "input-block": string;
  "label-top": string;
  "link-forgot": string;
  logo: string;
  onAutoFillCancel: string;
  onAutoFillStart: string;
  sign: string;
  "sign-form": string;
}
export const cssExports: CssExports;
export default cssExports;
