// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  root: string;
  buttonDisable: string;
  buttonEnable: string;
  changeFormText: string;
  error: string;
  eye: string;
  head: string;
  hide: string;
  inputBlock: string;
  labelTop: string;
  linkForgot: string;
  logo: string;
  onAutoFillCancel: string;
  onAutoFillStart: string;
  sign: string;
  signForm: string;
}
export const cssExports: CssExports;
export default cssExports;
